PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
PREFIX cti: <http://gic.ufrpe.br/cti/vocabulary/cti#>

SELECT ?ppg_nome 
       ?conceito 
       ((COUNT(DISTINCT ?producao) * 10) AS ?total_publi) 
       (AVG(COALESCE(?citacoes, 0)) AS ?media_citacoes)
WHERE {
  # 1. FUNIL: Isola a base de dados
  {
    SELECT ?ppg ?ppg_nome ?conceito WHERE {
      ?ict cti:sg_uf "PE" .
      ?ppg cti:sediado ?ict ;
           cti:nm_programa_ies ?ppg_nome ;
           cti:avaliado ?conceito_obj .
      ?conceito_obj cti:cd_conceito_programa ?conceito .
    }
  }
  
  # 2. Mapeamento de produções
  ?discente cti:vinculado ?ppg ;
            cti:nm_pessoa ?nomeAutor .
  ?autor a cti:Autor ;
         cti:nm_pessoa ?nomeAutor ;
         cti:autoria ?producao .
         
  OPTIONAL { ?producao cti:nr_citacoes_publicacao ?citacoes }
}
GROUP BY ?ppg ?ppg_nome ?conceito
ORDER BY DESC(?conceito) DESC(?total_ponderado)