PREFIX cti: <http://gic.ufrpe.br/cti/vocabulary/cti#>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>

SELECT 
    ?cdPPG 
    ?nomePPG 
    ?ano 
    (AVG(xsd:decimal(?citacoes)) AS ?mediaCitacoes)
WHERE {
    ?pub a cti:Producao_Cientifica ;
         cti:vinculada_ao_ppg ?ppg ;
         cti:an_base_producao ?ano ;
         cti:nr_citacoes_publicacao ?citacoes .

    ?ppg cti:cd_programa_ies ?cdPPG ;
         cti:nm_programa_ies ?nomePPG .

    FILTER(?ano >= 2017 && ?ano <= 2024)
}
GROUP BY ?cdPPG ?nomePPG ?ano
ORDER BY ?nomePPG ?ano