PREFIX cti: <http://gic.ufrpe.br/cti/vocabulary/cti#>

SELECT 
    ?cdPPG 
    ?nomePPG 
    ?ano 
    ((COUNT(DISTINCT ?pub)*10) AS ?totalProducoes)
WHERE {
    ?pub a cti:Producao_Cientifica ;
         cti:vinculada_ao_ppg ?ppg ;
         cti:an_base_producao ?ano .

    ?ppg cti:cd_programa_ies ?cdPPG ;
         cti:nm_programa_ies ?nomePPG .

    FILTER(?ano >= 2017 && ?ano <= 2024)
}
GROUP BY ?cdPPG ?nomePPG ?ano
ORDER BY ?nomePPG ?ano