PREFIX cti: <http://gic.ufrpe.br/cti/vocabulary/cti#>

SELECT ?anoProducao ?nomeAutor ?naturezaPub ?citacoesPub ?doiPublicacao
WHERE {
    ?autor a cti:Autor ;
           cti:nm_pessoa ?nomeAutor ;
           cti:autoria ?producao .

    ?producao a cti:Producao_Cientifica ;
              cti:an_base_producao ?anoProducao ;
              cti:ds_natureza ?naturezaPub ;
              cti:nr_citacoes_publicacao ?citacoesPub .

    OPTIONAL { ?producao cti:ds_doi ?doiPublicacao . }
}
ORDER BY DESC(?anoProducao) DESC(?citacoesPub)
LIMIT 100