PREFIX cti: <http://gic.ufrpe.br/cti/vocabulary/cti#>

SELECT
    ?cdPPG
    ?nomePPG
    ?ano
    ?conceito
WHERE {

    ?ppg a cti:PPG ;
         cti:cd_programa_ies ?cdPPG ;
         cti:nm_programa_ies ?nomePPG ;
         cti:avaliado ?avaliacao .

    ?avaliacao
         cti:an_base_conceito ?ano ;
         cti:cd_conceito_programa ?conceito .

    FILTER(?ano >= 2017 && ?ano <= 2024)

}
ORDER BY ?nomePPG ?ano